- scripts/experimental/optimization/full_setup.py
- scripts/experimental/optimization/optimization_interface.py
- scripts/experimental/optimization/run_optimization.py
- scripts/experimental/optimization/vehicle_and_mission_setup.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Drag/compute_aircraft_drag.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Drag/miscellaneous_drag_aircraft_ESDU.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Drag/parasite_drag_aircraft.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Drag/parasite_drag_fuselage.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Drag/parasite_drag_propulsor.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Drag/parasite_drag_pylon.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Drag/parasite_drag_wing.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Lift/compute_max_lift_coeff.py
- trunk/SUAVE/Methods/Geometry/Two_Dimensional/Planform/wing_fuel_volume.py
- trunk/SUAVE/Methods/Geometry/Two_Dimensional/Planform/wing_planform.py
- trunk/SUAVE/Methods/Performance/find_takeoff_weight_given_tofl.py
- trunk/SUAVE/Methods/Performance/size_mission_range_given_weights.py
- trunk/SUAVE/Methods/Weights/Correlations/Tube_Wing/empty.py
Embraer test case for a B737-800
> Feature opt structure

- scripts/experimental/optimization/optimization_interface.py
- scripts/experimental/optimization/run_optimization.py
Correct a bug: empenages areas (wetted, exposed) wasn't being updated after the sizing.
this was making the optimization not converge
> Updating optimization scripts

- trunk/SUAVE/Analyses/Mission/Segments/Climb/Constant_EAS_Constant_Rate.py
- trunk/SUAVE/Analyses/Mission/Segments/Climb/__init__.py
- trunk/SUAVE/Analyses/Mission/Segments/Descent/Constant_EAS_Constant_Rate.py
- trunk/SUAVE/Analyses/Mission/Segments/Descent/Unknown_Throttle.py
- trunk/SUAVE/Analyses/Mission/Segments/Descent/__init__.py
- trunk/SUAVE/Methods/Missions/Segments/Climb/Constant_EAS_Constant_Rate.py
- trunk/SUAVE/Methods/Missions/Segments/Climb/__init__.py
- trunk/SUAVE/Methods/Missions/Segments/Descent/Constant_EAS_Constant_Rate.py
- trunk/SUAVE/Methods/Missions/Segments/Descent/__init__.py
This is a minor addition, not the constant throttle segments which are in another branch.
> Add constant EAS constant rate climb and descent segments

- trunk/SUAVE/Analyses/Stability/Fidelity_Zero.py
- trunk/SUAVE/Components/Energy/Converters/Generator.py
- trunk/SUAVE/Components/Energy/Converters/Turbine.py
- trunk/SUAVE/Components/Energy/Converters/__init__.py
- trunk/SUAVE/Components/Energy/Networks/Turbofan.py
- trunk/SUAVE/Input_Output/Results/print_engine_data.py
- trunk/SUAVE/Input_Output/Results/print_mission_breakdown.py
- trunk/SUAVE/Input_Output/SUAVE/print_contents.py
- trunk/SUAVE/Methods/Flight_Dynamics/Dynamic_Stability/Full_Linearized_Equations/Supporting_Functions/__init__.py
- trunk/SUAVE/Methods/Flight_Dynamics/Dynamic_Stability/Full_Linearized_Equations/Supporting_Functions/cl_beta.py
- trunk/SUAVE/Methods/Flight_Dynamics/Dynamic_Stability/Full_Linearized_Equations/Supporting_Functions/cl_p.py
A number of simple features/improvements developed during the work on [Stratospheric Aerosol Geoengineering Aircraft (SAGA)](https://github.com/lukekulik/saga-one) design.
> SAGA research spin-offs

- README.md
- trunk/SUAVE/Methods/Utilities/__init__.py
- trunk/SUAVE/Methods/Utilities/latin_hypercube_sampling.py
LHS script. Rick gave me this file and I made some small changes and added a test function.
> Feature lhs

- trunk/SUAVE/Analyses/Mission/Segments/Single_Point/Set_Speed_Set_Altitude.py
- trunk/SUAVE/Analyses/Mission/Segments/Single_Point/__init__.py
- trunk/SUAVE/Analyses/Mission/Segments/__init__.py
- trunk/SUAVE/Components/Energy/Converters/Supersonic_Nozzle.py
- trunk/SUAVE/Methods/Missions/Segments/Single_Point/Set_Speed_Set_Altitude.py
- trunk/SUAVE/Methods/Missions/Segments/Single_Point/__init__.py
- trunk/SUAVE/Methods/Missions/Segments/__init__.py
This allows a single point to be evaluated by setting airspeed and altitude. X and Z acceleration default to zero but could also be set. The airspeed is assumed to be in the X direction only.
> Feature single point eval

- trunk/SUAVE/Methods/Aerodynamics/AERODAS/AERODAS_setup.py
- trunk/SUAVE/Methods/Aerodynamics/AERODAS/post_stall_coefficients.py
- trunk/SUAVE/Methods/Aerodynamics/AERODAS/pre_stall_coefficients.py
- trunk/SUAVE/Methods/Aerodynamics/AERODAS/section_properties.py
- trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Lift/compute_max_lift_coeff.py
> updates to AERODAS

- .travis.yml
Adding in coveralls to show our regression coverage.
> Feature test coveralls

- trunk/SUAVE/Input_Output/OpenVSP/get_vsp_areas.py
The fixes an issue with how the OpenVSP wetted area output was read.
> Fixed read script for new format

- PULL_REQUEST_TEMPLATE.md
Merge in the latest Develop branch changes to your branch
Remove .pyc files from your repository:
Linux/Mac
find . -name *.pyc -delete
Windows
del /S *.pyc
Run automatic regression and makes sure everything is passing
Did you make a new regression test that covers your new code?
Did you update your docstrings?
Did you update your headers to include your name and date?
Do a final compare with the Develop branch to be sure what you're changing
> Planes patch 1

- trunk/SUAVE/Methods/Aerodynamics/AVL/create_avl_datastructure.py
* Linux/Mac
* Windows
* del /S *.pyc
> Feature AVL

- trunk/SUAVE/Attributes/Propellants/Gaseous_H2.py
- trunk/SUAVE/Attributes/Propellants/Jet_A.py
- trunk/SUAVE/Attributes/Propellants/Jet_A1.py
- trunk/SUAVE/Attributes/Propellants/Propellant.py
This pull request fixes issues in printing as base python dicts don't print right
Pull Request Checklist
* Linux/Mac
* Windows
* del /S *.pyc
> Feature propellant fix

- trunk/SUAVE/Components/Wings/Wing.py
Ordering is preserved
* Linux/Mac
* Windows
* del /S *.pyc
> changing segment container type

- trunk/SUAVE/Core/Data.py
- trunk/SUAVE/Core/DataOrdered.py
I can't get it to indent like I want but it prints.
* Linux/Mac
* Windows
* del /S *.pyc
> Fix to allow ordered data to print correctly

- trunk/SUAVE/Input_Output/Results/print_weights.py
Fixed spelling of 'weight' in weight breakdown printing function.
> Fixed typos in weight breakdown printing function

- trunk/SUAVE/Input_Output/SUAVE/archive.py
* Linux/Mac
* Windows
* del /S *.pyc
> Fixing function type to check for a callable which is more general

- trunk/SUAVE/Input_Output/SUAVE/archive.py
* Linux/Mac
* Windows
* del /S *.pyc
> Redoing this archive thing

- trunk/SUAVE/Input_Output/SU2/write_SU2_cfg.py
* Linux/Mac
* Windows
* del /S *.pyc
> fixing aoa caps

- regression/scripts/variable_cruise_distance/variable_cruise_distance.py
- trunk/SUAVE/Analyses/Mission/All_At_Once.py
- trunk/SUAVE/Analyses/Mission/Segments/Conditions/State.py
- trunk/SUAVE/Analyses/Mission/Vary_Cruise/Given_Weight.py
- trunk/SUAVE/Methods/Missions/Segments/Common/Sub_Segments.py
- trunk/SUAVE/Methods/Missions/Segments/Cruise/Variable_Cruise_Distance.py
* Linux/Mac
* Windows
* del /S *.pyc
> Feature variable cruise

- regression/scripts/concorde/concorde.py
- trunk/SUAVE/Methods/Missions/Segments/Cruise/Constant_Mach_Constant_Altitude.py
- trunk/SUAVE/Methods/Missions/Segments/Cruise/Constant_Mach_Constant_Altitude_Loiter.py
This solves an issue with the altitude not being read correctly to determine speed of sound.
> fixed an issue with altitude in constant mach constant altitude

- trunk/SUAVE/Components/Energy/Networks/Turbofan.py
- trunk/SUAVE/Components/Fuselages/Fuselage.py
- trunk/SUAVE/Components/Fuselages/Segment.py
- trunk/SUAVE/Components/Fuselages/__init__.py
- trunk/SUAVE/Input_Output/OpenVSP/vsp_write.py
- trunk/SUAVE/Input_Output/OpenVSP/write_vsp_mesh.py
- trunk/SUAVE/Methods/Center_of_Gravity/compute_fuel_center_of_gravity_longitudinal_range.py
This allows sections to be specified and then written to an OpenVSP file along with the rest of the vehicle.
> Fuselages by section in OpenVSP

- regression/scripts/AVL/avl_files/aircraft.avl
- trunk/SUAVE/Components/Energy/Distributors/Electronic_Speed_Controller.py
- trunk/SUAVE/Components/Energy/Networks/Battery_Propeller.py
- trunk/SUAVE/Components/Energy/Networks/Lift_Forward_Propulsor.py
- trunk/SUAVE/Components/Energy/Networks/Solar.py
- trunk/SUAVE/Components/Energy/Networks/Solar_Low_Fidelity.py
* Linux/Mac
* Windows
* del /S *.pyc
> Feature esc fix

- trunk/setup.py
* Linux/Mac
* Windows
* del /S *.pyc
> Updated Setup.py

- README.md
* Linux/Mac
* Windows
* del /S *.pyc
> Updated Zenodo

- trunk/SUAVE/Components/Energy/Converters/Propeller.py
* Linux/Mac
* Windows
* del /S *.pyc
> initial commit

- trunk/SUAVE/Components/Energy/Networks/Solar.py
* Linux/Mac
* Windows
* del /S *.pyc
> fixing segment.state

- README.md
This pull request fixes the markdown file to remove the special c-cedilla in response to #321.
* Linux/Mac
* Windows
* del /S *.pyc
> removing special character

- .travis.yml
I am updating the travis to check the feature-pseudo_vtol_develop
* Linux/Mac
* Windows
* del /S *.pyc
> Updating the Travis

- trunk/SUAVE/Methods/Aerodynamics/Supersonic_Zero/Drag/compressibility_drag_total.py
changing "is not " to !=
Fixes #334 
* Linux/Mac
* Windows
* del /S *.pyc
> correction to syntax warning

- trunk/SUAVE/Methods/Missions/Segments/Ground/Common.py
Fixes #327 
Pull Request Checklist
* Linux/Mac
* Windows
* del /S *.pyc
> corrections to ground segment 

- trunk/SUAVE/.idea/.gitignore
- trunk/SUAVE/.idea/SUAVE.iml
* Linux/Mac
* Windows
* del /S *.pyc
> Feature hidden file removal

- trunk/SUAVE/Plots/Mission_Plots.py
* Linux/Mac
* Windows
* del /S *.pyc
> non scientific axes

- .travis.yml
* Linux/Mac
* Windows
* del /S *.pyc
> tracking jax develop for travis

- trunk/SUAVE/Methods/Missions/Segments/Climb/Constant_EAS_Constant_Rate.py
- trunk/SUAVE/Methods/Missions/Segments/Descent/Constant_EAS_Constant_Rate.py
This fixes a bug where a change in temperature creates an error in the sea level density on the constant EAS mission segments
* Linux/Mac
* Windows
* del /S *.pyc
> Fix constant eas

- trunk/SUAVE/Analyses/Aerodynamics/SU2_inviscid.py
An old import for pyplot hangs SUAVE on my system. Now it's updated to match current syntax.
> old pyplot import

- regression/scripts/segments/segment_test.py
Some how the last PR is causing travis to error, and only did so after completing the PR.
> regression fixes

- regression/scripts/Vehicles/Cessna_172.py
- regression/scripts/internal_combustion_propeller/ICE_Test.py
- trunk/SUAVE/Components/Energy/Converters/Internal_Combustion_Engine.py
- trunk/SUAVE/Components/Energy/Networks/Internal_Combustion_Propeller.py
- trunk/SUAVE/Methods/Weights/Correlations/General_Aviation/empty.py
Fixes for the internal combustion engine. The unpack and residuals were not correct.
> adding in convergence for internal combustion engine

- regression/scripts/concorde/concorde.py
- trunk/SUAVE/Input_Output/OpenVSP/__init__.py
- trunk/SUAVE/Input_Output/OpenVSP/get_vsp_measurements.py
This expands the wetted area function to also allow wetted volume calculations. It was tested locally against manual outputs.
> Option for Computing OpenVSP Volume

- trunk/SUAVE/Components/Wings/Wing.py
- trunk/SUAVE/Methods/Geometry/Two_Dimensional/Planform/wing_segmented_planform.py
After some vetting we found that there were some issues in the centroid location. I fixed this and also made some other minor changes.
> MAC Calculation Fixes

- regression/scripts/concorde/concorde.py
- trunk/SUAVE/Methods/Center_of_Gravity/compute_fuel_center_of_gravity_longitudinal_range.py
Add more unit options to the fuel CG plot.
> CG Plot Unit Options

- trunk/SUAVE/Input_Output/OpenVSP/vsp_write.py
Includes a number of changes to OpenVSP write that add new functionality.
> OpenVSP Write Updates

- trunk/SUAVE/Analyses/Aerodynamics/Markup.py
- trunk/SUAVE/Methods/Aerodynamics/Common/Fidelity_Zero/Drag/parasite_drag_wing.py
This creates an option to avoid overwriting the wetted area when using segment calculations.
> Fixed Wetted Area Option

- regression/automatic_regression.py
- regression/scripts/nonuniform_propeller_inflow/nonuniform_propeller_inflow.py
- trunk/SUAVE/Components/Energy/Converters/Propeller.py
- trunk/SUAVE/Methods/Aerodynamics/Common/Fidelity_Zero/Lift/VLM.py
- trunk/SUAVE/Plots/Propeller_Plots.py
* Linux/Mac
* Windows
* del /S *.pyc
> Feature nonuniform freestream

- trunk/SUAVE/Components/Energy/Converters/Propeller.py
- trunk/SUAVE/Components/Energy/Converters/Rotor.py
* Linux/Mac
* Windows
* del /S *.pyc
> PR to removed repetitive lines in Propeller and Rotor Scripts

- trunk/SUAVE/Methods/Weights/Buildups/eVTOL/empty.py
* Linux/Mac
* Windows
* del /S *.pyc
> fixing esc in evtol weight buildup

- regression/scripts/noise_fidelity_one/aircraft_noise.py
- trunk/SUAVE/Analyses/Noise/Fidelity_One.py
- trunk/SUAVE/Methods/Noise/Fidelity_One/Noise_Tools/SPL_harmonic_to_third_octave.py
- trunk/SUAVE/Methods/Propulsion/electric_motor_sizing.py
- trunk/SUAVE/Methods/Propulsion/propeller_design.py
- trunk/SUAVE/Plots/Geometry_Plots/plot_airfoil.py
- trunk/SUAVE/Plots/Propeller_Plots.py
* Linux/Mac
* Windows
* del /S *.pyc
> adding a few comments and once noise correction

- trunk/setup.py
* Linux/Mac
* Windows
* del /S *.pyc
> changing date and version

- README.md
* Linux/Mac
* Windows
* del /S *.pyc
> updated zenodo badge

- regression/scripts/Vehicles/Cessna_172.py
- regression/scripts/Vehicles/X57_Maxwell.py
- regression/scripts/internal_combustion_propeller/ICE_CS_Test.py
- regression/scripts/internal_combustion_propeller/ICE_Test.py
- regression/scripts/weights/weights.py
* Linux/Mac
* Windows
* del /S *.pyc
> correcting taper ratio

- trunk/SUAVE/Components/Energy/Converters/Propeller.py
- trunk/SUAVE/Input_Output/VTK/save_prop_vtk.py
- trunk/SUAVE/Methods/Geometry/Two_Dimensional/Cross_Section/Airfoil/import_airfoil_geometry.py
* Linux/Mac
* Windows
* del /S *.pyc
> small fixes

- trunk/SUAVE/Components/Energy/Converters/Propeller.py
* Linux/Mac
* Windows
* del /S *.pyc
> Rotor drag addition

- regression/scripts/Vehicles/Electric_Multicopter.py
- trunk/SUAVE/Methods/Propulsion/propeller_design.py
- trunk/SUAVE/Plots/Geometry_Plots/plot_vehicle.py
* Linux/Mac
* Windows
* del /S *.pyc
> adding rotor locations and fixing plotting bugs

- trunk/SUAVE/Components/Energy/Converters/Rotor.py
- trunk/SUAVE/Input_Output/VTK/save_vehicle_vtk.py
* Linux/Mac
* Windows
* del /S *.pyc
> fix for thrust vector in rotor.py

- trunk/SUAVE/Analyses/Aerodynamics/SU2_Euler_Super.py
- trunk/SUAVE/Analyses/Aerodynamics/SU2_inviscid_Super.py
* Linux/Mac
* Windows
* del /S *.pyc
> Fix euler super

- regression/scripts/Vehicles/X57_Maxwell_Mod2.py
- trunk/SUAVE/Components/Energy/Networks/Battery_Propeller.py
> Pitch Command Bug Fix 

- trunk/SUAVE/Methods/Aerodynamics/Common/Fidelity_Zero/Lift/generate_vortex_distribution.py
- trunk/SUAVE/Methods/Aerodynamics/Common/Fidelity_Zero/Lift/make_VLM_wings.py
This is a simple fix for a previously overlooked bug.
> Remove overlooked assumption that all wings have y-origins==0

- regression/scripts/B737/mission_B737.py
- regression/scripts/Vehicles/Boeing_737.py
- trunk/SUAVE/Methods/Flight_Dynamics/Static_Stability/compute_aero_derivatives.py
Adds control surface deflection derivatives to aero derivatives
> Feature control surface derivatives

- trunk/SUAVE/Plots/Mission_Plots.py
* Linux/Mac
* Windows
* del /S *.pyc
> fixing lift+cruise plots

- regression/scripts/variable_cruise_distance/variable_cruise_distance.py
- trunk/SUAVE/Analyses/Mission/Segments/Segment.py
- trunk/SUAVE/Components/Energy/Networks/Lift_Cruise.py
- trunk/SUAVE/Core/Arrays.py
- trunk/SUAVE/Core/ContainerOrdered.py
- trunk/SUAVE/Core/Data.py
- trunk/SUAVE/Core/DataOrdered.py
- trunk/SUAVE/Methods/Missions/Segments/Common/Sub_Segments.py
- trunk/SUAVE/Methods/Weights/Buildups/eVTOL/empty.py
> Fix various

- appveyor.yml
* Linux/Mac
* Windows
* del /S *.pyc
> updating appveyor

- regression/scripts/solar_network/solar_network.py
- trunk/SUAVE/Components/Energy/Networks/Battery_Cell_Cycler.py
- trunk/SUAVE/Components/Energy/Networks/Battery_Propeller.py
- trunk/SUAVE/Components/Energy/Networks/Lift_Cruise.py
- trunk/SUAVE/Components/Energy/Networks/Solar.py
- trunk/SUAVE/Components/Energy/Storages/Batteries/Constant_Mass/Lithium_Ion.py
- trunk/SUAVE/Components/Energy/Storages/Batteries/Constant_Mass/Lithium_Ion_LiFePO4_18650.py
- trunk/SUAVE/Components/Energy/Storages/Batteries/Constant_Mass/Lithium_Ion_LiNiMnCoO2_18650.py
- trunk/SUAVE/Methods/Power/Battery/append_initial_battery_conditions.py
* Linux/Mac
* Windows
* del /S *.pyc
> fixed battery for solar UAV

- regression/scripts/AVL/avl_files/commands_01.deck
- regression/scripts/AVL/avl_files/commands_02.deck
- regression/scripts/AVL/avl_files/commands_03.deck
- regression/scripts/AVL/avl_files/commands_04.deck
- regression/scripts/AVL/avl_files/commands_05.deck
- regression/scripts/AVL/avl_files/commands_06.deck
- regression/scripts/Vehicles/Boeing_737.py
- regression/scripts/solar_network/solar_network.py
- trunk/SUAVE/Analyses/Mission/Segments/Conditions/Aerodynamics.py
- trunk/SUAVE/Components/Energy/Networks/Solar_Low_Fidelity.py
- trunk/SUAVE/Components/Energy/Storages/Batteries/Battery.py
- trunk/SUAVE/Components/Energy/Storages/Batteries/Constant_Mass/Lithium_Ion.py
- trunk/SUAVE/Components/Nacelles/Nacelle.py
- trunk/SUAVE/Input_Output/OpenVSP/write_vsp_mesh.py
- trunk/SUAVE/Methods/Aerodynamics/AVL/write_input_deck.py
- trunk/SUAVE/Methods/Geometry/Two_Dimensional/Cross_Section/Propulsion/compute_turbofan_geometry.py
- trunk/SUAVE/Plots/Geometry/plot_vehicle.py
- trunk/SUAVE/Plots/Performance/Mission_Plots.py
* Linux/Mac
* Windows
* del /S *.pyc
> Fix tutorials

- README.md
- doc/suave_config
- trunk/setup.py
* Linux/Mac
* Windows
* del /S *.pyc
> updates for after a release

- trunk/SUAVE/Components/Energy/Networks/Lift_Cruise.py
- trunk/SUAVE/Input_Output/OpenVSP/vsp_wing.py
- trunk/SUAVE/Methods/Aerodynamics/Common/Fidelity_Zero/Lift/generate_vortex_distribution.py
* Linux/Mac
* Windows
* del /S *.pyc
> Corrections to VLM and Lift Cruise network

- trunk/SUAVE/Input_Output/OpenVSP/vsp_nacelle.py
* Linux/Mac
* Windows
* del /S *.pyc
> fixing nacelle scaling

- regression/scripts/segments/segment_test.py
- trunk/SUAVE/Methods/Missions/Segments/Descent/Constant_EAS_Constant_Rate.py
* Linux/Mac
* Windows
* del /S *.pyc
> fix eas bug

- appveyor.yml
* Linux/Mac
* Windows
* del /S *.pyc
> appveyor for a specific version

- doc/suave_config
- trunk/SUAVE/Components/Airfoils/Airfoil.py
- trunk/SUAVE/Components/Airfoils/__init__.py
- trunk/SUAVE/Components/Energy/Charging/__init__.py
- trunk/SUAVE/Components/Landing_Gear/__init__.py
- trunk/SUAVE/Components/Lofted_Body_Segment/Segment.py
- trunk/SUAVE/Components/Lofted_Body_Segment/__init__.py
- trunk/SUAVE/Components/Nacelles/Nacelle.py
- trunk/SUAVE/Methods/Aerodynamics/Common/Gas_Dynamics/Oblique_Shock.py
- trunk/SUAVE/Methods/Aerodynamics/Common/Gas_Dynamics/__init__.py
- trunk/SUAVE/Methods/Noise/Certification/__init__.py
- trunk/SUAVE/Methods/Propulsion/Rotor_Wake/Fidelity_One/__init__.py
- trunk/SUAVE/Methods/Propulsion/Rotor_Wake/Fidelity_One/compute_wake_induced_velocity.py
- trunk/SUAVE/Methods/Propulsion/Rotor_Wake/Fidelity_Zero/__init__.py
- trunk/SUAVE/Methods/Propulsion/Rotor_Wake/Fidelity_Zero/compute_fidelity_zero_induced_velocity.py
- trunk/SUAVE/Methods/Propulsion/Rotor_Wake/Fidelity_Zero/compute_wake_contraction_matrix.py
- trunk/SUAVE/Methods/Propulsion/Rotor_Wake/Fidelity_Zero/fidelity_zero_wake_convergence.py
- trunk/SUAVE/Methods/Propulsion/Rotor_Wake/__init__.py
- trunk/SUAVE/Methods/Propulsion/__init__.py
- trunk/SUAVE/Methods/Weights/Buildups/eVTOL/__init__.py
- trunk/SUAVE/Plots/Geometry/__init__.py
- trunk/SUAVE/Plots/Performance/Mission_Plots.py
- trunk/SUAVE/Plots/Performance/Propeller_Plots.py
- trunk/SUAVE/Plots/Performance/__init__.py
* Linux/Mac
* Windows
* del /S *.pyc
> fixes for release
